# Generated by Django 3.1.1 on 2021-06-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='quiz',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='radioshow',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
