# Generated by Django 3.1.1 on 2021-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0003_radiouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='einsendeschluss',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
