# Generated by Django 3.1.1 on 2021-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0004_radioshow_einsendeschluss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioshow',
            name='einsendeschluss',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
