# Generated by Django 3.1.1 on 2021-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0005_auto_20210604_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadioUser',
        ),
        migrations.RemoveField(
            model_name='radioshow',
            name='einsendeschluss',
        ),
        migrations.AddField(
            model_name='radioshow',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
