# Generated by Django 3.1.1 on 2021-06-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0009_songwishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songwishes',
            name='song_wishes',
        ),
        migrations.AlterField(
            model_name='songwishes',
            name='author',
            field=models.CharField(max_length=1000),
        ),
    ]
