# Generated by Django 3.1.1 on 2021-06-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0010_auto_20210606_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
