# Generated by Django 3.1.1 on 2021-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0011_radioshow_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
