# Generated by Django 3.1.1 on 2021-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0012_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
