# Generated by Django 3.1.1 on 2021-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0014_auto_20210619_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songwishes',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
