# Generated by Django 3.1.1 on 2021-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0015_auto_20210619_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='songwishes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
