# Generated by Django 3.1.1 on 2021-06-19 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radioready', '0016_songwishes_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='songwishes',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songwishes',
            name='song',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
