# Generated by Django 3.1.1 on 2021-06-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0017_auto_20210619_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songwishes',
            options={'ordering': ['-created']},
        ),
    ]
