# Generated by Django 3.1.1 on 2021-06-19 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radioready', '0018_auto_20210619_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songwishes',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='songwishes',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songwishes',
            name='song',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
