# Generated by Django 3.1.1 on 2021-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0020_radioshow_staffel'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioshow',
            name='hide_until',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
