# Generated by Django 3.1.1 on 2021-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0022_auto_20210704_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioshow',
            name='hide_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
