# Generated by Django 3.1.1 on 2021-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0023_auto_20210704_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioshow',
            name='hide_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
