# Generated by Django 3.1.1 on 2021-07-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0026_radioumfrage_umfrageantworten'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioumfrage',
            old_name='Question',
            new_name='question',
        ),
    ]
