# Generated by Django 3.1.1 on 2021-07-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0027_auto_20210711_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioumfrage',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='radioready.umfrageantworten', verbose_name='Deine Antwort:'),
        ),
    ]
