# Generated by Django 3.1.1 on 2021-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0028_auto_20210711_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField(blank=True, default='', max_length=1000, verbose_name='Dein Kommentar')),
                ('kommentar_antwort', models.TextField(blank=True, default='', max_length=1000, verbose_name='Die Antwort zu dem Kommentar')),
            ],
        ),
        migrations.DeleteModel(
            name='RadioUmfrage',
        ),
        migrations.DeleteModel(
            name='UmfrageAntworten',
        ),
    ]
