# Generated by Django 3.1.1 on 2021-07-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioready', '0032_auto_20210711_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kommentare',
            name='kommentar',
            field=models.TextField(max_length=1000, verbose_name='Dein Kommentar:'),
        ),
    ]
