# Generated by Django 3.0.7 on 2020-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeutschesWort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnglischesWort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=100)),
            ],
        ),
    ]
