# Generated by Django 3.1 on 2020-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englischeswort',
            name='dwort',
            field=models.ManyToManyField(to='v_trainer.DeutschesWort'),
        ),
    ]
