# Generated by Django 3.1.1 on 2020-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0003_auto_20200811_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeutschTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fehler', models.PositiveIntegerField(verbose_name='fehler')),
                ('dwort', models.ManyToManyField(related_name='deutsch_test_woerter', to='v_trainer.DeutschesWort')),
            ],
        ),
    ]
