# Generated by Django 3.1.1 on 2020-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0005_auto_20200927_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deutschtest',
            name='fehler',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='fehler'),
        ),
    ]
