# Generated by Django 3.1.1 on 2021-01-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v_trainer', '0007_deutschtest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deutscheswort',
            name='wort',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EnglischTestEineVokalel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_englisches_wort_1', models.CharField(blank=True, max_length=120, null=True)),
                ('englisches_wort_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_1', to='v_trainer.englischeswort')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
