# Generated by Django 3.1.1 on 2021-02-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0008_auto_20210123_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeutschTest',
        ),
    ]
