# Generated by Django 3.1.1 on 2021-05-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0010_deutschtesteinevokalel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deutschtesteinevokalel',
            old_name='antwort_deutsches_wort_1',
            new_name='antwort_auf_deutsches_wort_1',
        ),
    ]
