# Generated by Django 3.1.1 on 2021-07-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0011_auto_20210513_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deutschtesteinevokalel',
            name='antwort_auf_deutsches_wort_1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung'),
        ),
        migrations.AlterField(
            model_name='deutschtesteinevokalel',
            name='deutsches_wort_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deutsch_test_wort_1', to='v_trainer.deutscheswort', verbose_name='Zu übersetzendes Wort'),
        ),
        migrations.AlterField(
            model_name='englischtesteinevokalel',
            name='antwort_englisches_wort_1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung'),
        ),
        migrations.AlterField(
            model_name='englischtesteinevokalel',
            name='englisches_wort_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_1', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort'),
        ),
    ]
