# Generated by Django 3.1.1 on 2021-07-06 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v_trainer', '0012_auto_20210706_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateinTestZehnVokalel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_lateinisches_wort_1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 1')),
                ('antwort_lateinisches_wort_2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 2')),
                ('antwort_lateinisches_wort_3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 3')),
                ('antwort_lateinisches_wort_4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 4')),
                ('antwort_lateinisches_wort_5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 5')),
                ('antwort_lateinisches_wort_6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 6')),
                ('antwort_lateinisches_wort_7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 7')),
                ('antwort_lateinisches_wort_8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 8')),
                ('antwort_lateinisches_wort_9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 9')),
                ('antwort_lateinisches_wort_10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 10')),
                ('lateinisches_wort_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_1', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 1')),
                ('lateinisches_wort_10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_10', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 10')),
                ('lateinisches_wort_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_2', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 2')),
                ('lateinisches_wort_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_3', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 3')),
                ('lateinisches_wort_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_4', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 4')),
                ('lateinisches_wort_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_5', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 5')),
                ('lateinisches_wort_6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_6', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 6')),
                ('lateinisches_wort_7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_7', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 7')),
                ('lateinisches_wort_8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_8', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 8')),
                ('lateinisches_wort_9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latein_test_wort_9', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 9')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LateinischesWort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wort', models.CharField(max_length=100, verbose_name='ewort')),
                ('dwort', models.ManyToManyField(related_name='list_of_deutschewords', to='v_trainer.DeutschesWort')),
            ],
        ),
    ]
