# Generated by Django 3.1.1 on 2021-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0014_auto_20210706_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deutscheswort',
            name='wort',
            field=models.CharField(max_length=100, unique=True, verbose_name='Wort'),
        ),
        migrations.AlterField(
            model_name='englischeswort',
            name='wort',
            field=models.CharField(max_length=100, unique=True, verbose_name='Wort'),
        ),
        migrations.AlterField(
            model_name='lateinischeswort',
            name='wort',
            field=models.CharField(max_length=100, unique=True, verbose_name='Wort'),
        ),
    ]
