# Generated by Django 3.1.1 on 2021-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0015_auto_20210707_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='FahneUeberschrift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahne_ueberschrift', models.CharField(max_length=100, unique=True, verbose_name='Klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=100, unique=True, verbose_name='Klasse')),
            ],
        ),
        migrations.CreateModel(
            name='LektionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lektion_unit', models.CharField(max_length=100, unique=True, verbose_name='Klasse')),
            ],
        ),
    ]
