# Generated by Django 3.1.1 on 2021-07-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0016_fahneueberschrift_klasse_lektionunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FahneUeberschrift',
        ),
        migrations.DeleteModel(
            name='Klasse',
        ),
        migrations.DeleteModel(
            name='LektionUnit',
        ),
    ]
