# Generated by Django 3.1.1 on 2021-07-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v_trainer', '0017_auto_20210707_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglischTestZehnVokalel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_englisches_wort_1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 1')),
                ('antwort_englisches_wort_2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 2')),
                ('antwort_englisches_wort_3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 3')),
                ('antwort_englisches_wort_4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 4')),
                ('antwort_englisches_wort_5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 5')),
                ('antwort_englisches_wort_6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 6')),
                ('antwort_englisches_wort_7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 7')),
                ('antwort_englisches_wort_8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 8')),
                ('antwort_englisches_wort_9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 9')),
                ('antwort_englisches_wort_10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Übersetzung zu Wort 10')),
                ('englisches_wort_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_1', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 1')),
                ('englisches_wort_10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_10', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 10')),
                ('englisches_wort_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_2', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 2')),
                ('englisches_wort_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_3', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 3')),
                ('englisches_wort_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_4', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 4')),
                ('englisches_wort_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_5', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 5')),
                ('englisches_wort_6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_6', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 6')),
                ('englisches_wort_7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_7', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 7')),
                ('englisches_wort_8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_8', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 8')),
                ('englisches_wort_9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_9', to='v_trainer.lateinischeswort', verbose_name='Zu übersetzendes Wort 9')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
