# Generated by Django 3.1.1 on 2021-07-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0018_englischtestzehnvokalel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_wort_1', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 1'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_10', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 10'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_2', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 2'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_3', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 3'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_4', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 4'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_5', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 5'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_6', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 6'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_7', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 7'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_8', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 8'),
        ),
        migrations.AlterField(
            model_name='englischtestzehnvokalel',
            name='englisches_wort_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englisch_test_wort_9', to='v_trainer.englischeswort', verbose_name='Zu übersetzendes Wort 9'),
        ),
    ]
