# Generated by Django 3.1.1 on 2021-07-10 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v_trainer', '0020_deutschtestzehnvokalel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englischtesteinevokalel',
            name='englisches_wort_1',
        ),
        migrations.RemoveField(
            model_name='englischtesteinevokalel',
            name='user',
        ),
        migrations.AddField(
            model_name='lateintestzehnvokalel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DeutschTestEineVokalel',
        ),
        migrations.DeleteModel(
            name='EnglischTestEineVokalel',
        ),
    ]
