# Generated by Django 3.1.1 on 2021-07-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_trainer', '0021_auto_20210710_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lateintestzehnvokalel',
            name='creator',
        ),
    ]
