from .deutscheswort import DeutschesWort
from .englischeswort import EnglischesWort
from .englischtest_1_vokabel import EnglischTestEineVokalel
from .deutschtest_1_vokabel import DeutschTestEineVokalel
